#!/usr/bin/env node
import assert from"node:assert/strict";import fs from"node:fs";import os from"node:os";import path from"node:path";import{spawnSync}from"node:child_process";
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"brand-distinctiveness-")),validator=path.resolve("skills/brand/scripts/validate-brand-distinctiveness.mjs"),write=v=>{const f=path.join(dir,`${Math.random()}.json`);fs.writeFileSync(f,JSON.stringify(v));return f},run=v=>spawnSync(process.execPath,[validator,"--assessment",write(v)],{encoding:"utf8"});
const dimensions=Object.fromEntries(["visualMass","asset","composition","type","motion"].map(n=>[n,{score:3,evidenceRefs:[`ev-${n}`]}]));
const base={schema:"brand-distinctiveness-assessment/v1",mode:"apply-host",pageCapacity:"high",readOnly:true,productionCodeMutations:[],statuses:{workflowCompletion:"PASS",businessSafety:"PASS"},viewportPairs:[{name:"desktop",width:1280,height:720,sameViewport:true,sourceViewport:{width:1280,height:720},hostViewport:{width:1280,height:720},sourceScreenshot:"source.png",hostScreenshot:"host.png"}],blindMask:{brandNames:true,logos:true,explicitBrandText:true,maskedHostScreenshot:"host-masked.png"},blindRecognition:{verdict:"PASS",reviewerExecutionId:"qa-fresh-1",recognizedTraits:["layered stage"]},dimensions,signals:[{id:"stage",dimension:"visualMass",kind:"surface-stage",visible:true,viewportAreaRatio:.32,evidenceRefs:["ev-visualMass"]},{id:"hero",dimension:"asset",kind:"character-art",visible:true,viewportAreaRatio:.24,evidenceRefs:["ev-asset"]},{id:"stack",dimension:"composition",kind:"asymmetric-layering",visible:true,viewportAreaRatio:.18,evidenceRefs:["ev-composition"]}],blockingFindings:[{code:"DISTINCTIVENESS_WEAK"}],failureOwnerRole:"designDirectorOrchestrator"};
assert.equal(run(base).status,0,"three material cross-dimension signals should pass");
assert.notEqual(run({...base,dimensions:{...dimensions,visualMass:{score:1,evidenceRefs:["archive"]},composition:{score:1,evidenceRefs:["archive"]}},signals:[{id:"mono",dimension:"type",kind:"small-signature",smallSignature:true,visible:true,viewportAreaRatio:.02,evidenceRefs:["archive"]},{id:"wheel",dimension:"asset",kind:"micro-icon",visible:true,viewportAreaRatio:.01,evidenceRefs:["icon"]}]}).status,0,"black/white archive plus small icon must fail");
assert.notEqual(run({...base,signals:[{id:"name",dimension:"type",kind:"brand-name",visible:true,viewportAreaRatio:.12,evidenceRefs:["name"]},{id:"logo",dimension:"asset",kind:"logo",visible:true,viewportAreaRatio:.25,evidenceRefs:["logo"]}]}).status,0,"logo/name only must fail");
console.log("validate-brand-distinctiveness tests passed");
