#!/usr/bin/env node
import assert from "node:assert/strict";import fs from "node:fs";import os from "node:os";import path from "node:path";import{spawnSync}from"node:child_process";
const dir=fs.mkdtempSync(path.join(os.tmpdir(),"brand-host-gate-")),validator=path.resolve("skills/brand/scripts/validate-host-apply-gate.mjs"),write=(n,v)=>{const f=path.join(dir,n);fs.writeFileSync(f,JSON.stringify(v));return f};
const probes=["root-surface","primary-control","representative-card","active-state"].map((role,sourceOrder)=>({role,selector:`.host .${role}`,elementCount:1,property:"background-color",expectedValue:"rgb(1, 2, 3)",computedValue:"rgb(1, 2, 3)",winningRule:{selector:`.host .${role}`,stylesheet:"host-theme.css",specificity:[0,2,0],sourceOrder}}));
const receipt={mappingStatus:"PARTIAL_STYLE_ONLY",coverageWording:"conservative-application",dangouiRuntimeCoverage:0,themeLoadOrderProof:{contractVersion:1,observations:[{phase:"cold-load",themeStylesheetCount:1,stylesheetsInOrder:["host.css","theme.css"],laterWinningStylesheets:[]},{phase:"route-navigation",themeStylesheetCount:1,stylesheetsInOrder:["host.css","theme.css"],laterWinningStylesheets:[]}]},renderedCascadeProof:{previewUrl:"http://localhost:1000/host",capturedAt:"2026-09-06T00:00:00Z",executionId:"impl-2",viewports:[{name:"desktop",width:1440,height:900,probes},{name:"mobile",width:390,height:844,probes}]},renderedBrandSignatures:[{id:"sig-type",selector:".host-title",elementCount:1,visible:true,evidenceRefs:["ev-font"],visibleContribution:"Distinct display type is visible."}]},capability={status:"DANGOOUI_RUNTIME_UNAVAILABLE",runtimeAvailable:false},plan={capacity:"high",brandSignatures:[{id:"sig-type",role:"display-type",placement:"masthead",evidenceRefs:["ev-font"],distinctivenessClaim:"Observed display face distinguishes the masthead."}]};
const distinctiveness={ok:true,gate:"brand-distinctiveness/v1",statuses:{workflowCompletion:"PASS",businessSafety:"PASS",visualDistinctiveness:"PASS"}};
const gaps={schema:"dangoui-capability-gaps/v1",source:{brand:"fixture",host:"fixture",platform:"h5",dangouiVersion:"3.6.16"},privacy:{networkSubmission:"disabled"},discovery:{total:0},summary:{total:0,capabilityGaps:0,correctBoundaries:0,unclassified:0},items:[]};
const run=(r=receipt,c=capability,p=plan,qa,d=distinctiveness,g=gaps)=>spawnSync(process.execPath,[validator,"--receipt",write(`r-${Math.random()}.json`,r),"--capability-audit",write(`c-${Math.random()}.json`,c),"--plan",write(`p-${Math.random()}.json`,p),"--distinctiveness",write(`d-${Math.random()}.json`,d),"--capability-gaps",write(`g-${Math.random()}.json`,g),...(qa?["--qa",write(`q-${Math.random()}.json`,qa)]:[])],{encoding:"utf8"});
const runWithoutGaps=()=>spawnSync(process.execPath,[validator,"--receipt",write("missing-gaps-r.json",receipt),"--capability-audit",write("missing-gaps-c.json",capability),"--plan",write("missing-gaps-p.json",plan),"--distinctiveness",write("missing-gaps-d.json",distinctiveness)],{encoding:"utf8"});
assert.equal(run().status,0);assert.notEqual(runWithoutGaps().status,0);assert.notEqual(run({...receipt,themeLoadOrderProof:{contractVersion:1,observations:[]}}).status,0);assert.notEqual(run({...receipt,themeLoadOrderProof:{contractVersion:1,observations:[receipt.themeLoadOrderProof.observations[0],{...receipt.themeLoadOrderProof.observations[1],laterWinningStylesheets:["route.css"]}]}}).status,0);assert.notEqual(run({...receipt,renderedCascadeProof:{...receipt.renderedCascadeProof,viewports:receipt.renderedCascadeProof.viewports.slice(0,1)}}).status,0);assert.notEqual(run({...receipt,mappingStatus:"COMPLETE",coverageWording:"complete-style-preview"}).status,0);assert.notEqual(run(receipt,capability,{capacity:"high",brandSignatures:[]}).status,0);assert.notEqual(run(receipt,capability,plan,{verdict:"FAIL",qaExecutionId:"qa-1",productionCodeMutations:["src/theme.css"],blockingFindings:[],failureOwnerRole:"visualQA"}).status,0);assert.equal(run(receipt,capability,plan,{verdict:"PASS",qaExecutionId:"qa-2",previousQaExecutionId:"qa-1",repairedImplementationExecutionId:"impl-2",productionCodeMutations:[]}).status,0);assert.notEqual(run(receipt,capability,plan,undefined,{ok:false,gate:"brand-distinctiveness/v1",statuses:{visualDistinctiveness:"FAIL"}}).status,0);console.log("validate-host-apply-gate tests passed");
